name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # 生成总统计卡片
      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&locale=en
          path: imgs/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # 生成语言统计卡片
      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&langs_count=6&locale=en
          path: imgs/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - name: Opened on user's repositories
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.followup.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_followup: yes

      - name: Opened by user
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.followup.user.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_sections: user

      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.notable.indepth.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes

      # 提交生成的卡片到仓库
      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add imgs/*.svg
          git commit -m "Update README cards" || exit 0
          git push